spring:
  application:
    name: backend

  server:
    port: ${PORT:8080}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/greentech_db}

  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY:sk-435906190b884e668ac1e16c72634c17}
      base-url: https://api.deepseek.com/chat/completions
      model: deepseek-chat

  docker:
    compose:
      enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:itsmoustir@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:zesm lbav korz iiec}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: "*"

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

app:
  jwtSecret: ${APP_JWT_SECRET:sqbddsjvqfhjskhlfdskjlhfdlskqgfsldbfhkdskflhsdhklfsqdhkfgqhsdklfhk}
  jwtExpirationMs: 86400000

