spring:
  application:
    name: backend

  server:
    port: 8080

  data:
    mongodb:
      uri: mongodb://localhost:27017/greentech_db

  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat



app :
   jwtSecret :
    sqbddsjvqfhjskhlfdskjlhfdlskqgfsldbfhkdskflhsdhklfsqdhkfgqhsdklfhk
   jwtExpirationMs :
      36000