import { StyleSheet } from 'react-native';
// 👇 YOU WERE MISSING THIS IMPORT
import colors from './colors'; // Adjust this path if 'colors.js' is in a different folder

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background, // Now this works
    },
    header: {
        padding: 20,
        paddingTop: 10,
    },
    welcome: {
        marginBottom: 16,
    },
    welcomeTitle: {
        fontSize: 28,
        fontWeight: '700',
        color: colors.textPrimary,
        marginBottom: 4,
    },
    welcomeSubtitle: {
        fontSize: 14,
        color: colors.textSecondary,
    },
    levelCard: {
        backgroundColor: colors.cardBackground,
        marginHorizontal: 20,
        marginBottom: 20,
        padding: 20,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: colors.cardBorder,
    },
    levelInfo: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    levelBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    levelText: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.accent,
    },
    levelPoints: {
        fontSize: 13,
        fontWeight: '600',
        color: colors.textPrimary,
    },
    progressBarContainer: {
        height: 10,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 10,
        overflow: 'hidden',
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: colors.accent,
        borderRadius: 10,
    },
    statsGrid: {
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    statsRow: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 12,
    },
    statCard: {
        flex: 1,
        backgroundColor: colors.cardBackground,
        borderRadius: 16,
        padding: 16,
        gap: 12,
        borderWidth: 1,
        borderColor: colors.cardBorder,
    },
    largeCard: {
        width: '100%',
        flexDirection: 'row',
    },
    statIcon: {
        width: 56,
        height: 56,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    statContent: {
        flex: 1,
    },
    statLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: colors.textSecondary,
        textTransform: 'uppercase',
        marginBottom: 6,
    },
    statValue: {
        fontSize: 28,
        fontWeight: '700',
        color: colors.textPrimary,
        marginBottom: 2,
    },
    statSubtitle: {
        fontSize: 12,
        color: colors.textSecondary,
    },
    rankProgress: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginTop: 10,
    },
    rankBar: {
        flex: 1,
        height: 5,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 10,
        overflow: 'hidden',
    },
    rankFill: {
        height: '100%',
        backgroundColor: '#667eea',
        borderRadius: 10,
    },
    rankPercentage: {
        fontSize: 11,
        fontWeight: '600',
        color: colors.accent,
    },
    equivalents: {
        gap: 8,
        marginTop: 10,
    },
    equivalentItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    equivalentText: {
        fontSize: 12,
        color: colors.textSecondary,
    },
    section: {
        backgroundColor: colors.cardBackground,
        marginHorizontal: 20,
        marginBottom: 20,
        padding: 20,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: colors.cardBorder,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    sectionTitle: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    sectionTitleText: {
        fontSize: 18,
        fontWeight: '700',
        color: colors.textPrimary,
    },
    badgeCount: {
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.cardBorder,
    },
    badgeCountText: {
        fontSize: 12,
        fontWeight: '600',
        color: colors.textSecondary,
    },
    badgesGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    badgeItem: {
        width: '30%',
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        borderWidth: 2,
        borderColor: colors.accent,
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        gap: 8,
        position: 'relative',
    },
    badgeLocked: {
        opacity: 0.5,
        borderColor: colors.cardBorder,
    },
    badgeIcon: {
        fontSize: 36,
    },
    badgeName: {
        fontSize: 11,
        fontWeight: '600',
        color: colors.textPrimary,
        textAlign: 'center',
    },
    lockIcon: {
        position: 'absolute',
        top: 8,
        right: 8,
    },
    transportGrid: {
        gap: 12,
    },
    transportRow: {
        flexDirection: 'row',
        gap: 12,
    },
    transportCard: {
        flex: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderWidth: 1,
        borderColor: colors.cardBorder,
        borderRadius: 12,
        padding: 16,
    },
    transportFullWidth: {
        flex: 'none',
        width: '100%',
    },
    transportHighlight: {
        borderColor: colors.accent,
        backgroundColor: 'rgba(42, 157, 111, 0.1)',
    },
    transportLabel: {
        fontSize: 11,
        fontWeight: '600',
        color: colors.textSecondary,
        textTransform: 'uppercase',
        marginBottom: 6,
    },
    transportValue: {
        fontSize: 24,
        fontWeight: '700',
        color: colors.textPrimary,
        marginBottom: 8,
    },
    transportDetail: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    transportDetailText: {
        fontSize: 12,
        color: colors.textSecondary,
    },
    transportComparison: {
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: colors.cardBorder,
    },
    comparisonLabel: {
        fontSize: 11,
        color: colors.textSecondary,
        marginBottom: 4,
    },
    comparisonValue: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.textPrimary,
        marginBottom: 8,
    },
    comparisonBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: 'rgba(42, 157, 111, 0.2)',
        borderWidth: 1,
        borderColor: colors.accent,
        borderRadius: 12,
        paddingHorizontal: 8,
        paddingVertical: 4,
        alignSelf: 'flex-start',
    },
    comparisonText: {
        fontSize: 11,
        fontWeight: '600',
        color: colors.accent,
    },
    periodSelector: {
        flexDirection: 'row',
        gap: 6,
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        padding: 4,
        borderRadius: 10,
    },
    periodBtn: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
    },
    periodBtnActive: {
        backgroundColor: colors.accent,
    },
    periodBtnText: {
        fontSize: 12,
        fontWeight: '600',
        color: colors.textSecondary,
    },
    periodBtnTextActive: {
        color: colors.textPrimary,
    },
    performanceGrid: {
        gap: 12,
    },
    performanceRow: {
        flexDirection: 'row',
        gap: 12,
    },
    performanceItem: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        gap: 10,
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderWidth: 1,
        borderColor: colors.cardBorder,
        borderRadius: 12,
        padding: 14,
    },
    perfIcon: {
        width: 44,
        height: 44,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    perfData: {
        alignItems: 'center',
    },
    perfLabel: {
        fontSize: 10,
        fontWeight: '600',
        color: colors.textSecondary,
        textTransform: 'uppercase',
        marginBottom: 4,
        textAlign: 'center',
    },
    perfValue: {
        fontSize: 18,
        fontWeight: '700',
        color: colors.textPrimary,
    },
    trackingCard: {
        backgroundColor: colors.cardBackground,
        borderRadius: 16,
        padding: 20,
        marginHorizontal: 20,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: colors.cardBorder,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    trackingHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
    },
    trackingTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginLeft: 10,
        color: colors.textPrimary,
    },
    statusText: {
        textAlign: 'center',
        marginBottom: 20,
        color: colors.textSecondary,
        fontStyle: 'italic',
        fontSize: 14,
    },
    trackButton: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 15,
        borderRadius: 10,
    },
    startBtn: {
        backgroundColor: '#2ecc71',
    },
    stopBtn: {
        backgroundColor: '#e74c3c',
    },
    btnText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
        marginLeft: 10,
    },
});

export default styles;